### ISSUE TITLE
Upgrade dependency to OkHttp3

### ISSUE THREAD

**Issue by evfool** [location-iq/locationiq-java-client#2]
the okHttp3 library used by this project is fairly old, would you accept a pull request with a working upgrade to okHttp3, released more than 3 years ago?

**Comment by rocainunwired** [comment]
This java-client is generated by using OpenAPI specifications & [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator). Pull request for this issue to this repo is not advisable as the library would be updated back with the okhttp3 library used by the generator when updates to specifications are made. But you could contribute to the OpenAPI generator repo and we'll pull the latest changes to the libraries from there.

**Comment by evfool** [comment]
OpenAPI Generator already has support (in beta state only though - https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.0.0-beta2) to generate OkHttp3 bindings (okhttp generator defaults have been upgraded to okhttp3 from okhttp2 - https://github.com/OpenAPITools/openapi-generator/pull/1897). Is there a way to request a java client generated with the new OpenAPI generator or to receive the files the client is generated from to do the generation myself?

**Comment by rocainunwired** [comment]
@evfool We'll push our spec file by tomorrow, and you could use it to generate the client directly with the OpenAPI version of your choice.

**Comment by evfool** [comment]
Thank you, that will be very helpful.

**Comment by rocainunwired** [comment]
We have pushed our spec onto a new repo over [here.](https://github.com/location-iq/locationiq-openapi-spec) You could use it to generate the client directly with the OpenAPI generator.

**Comment by evfool** [comment]
Thanks.
